### ISSUE TITLE
Scheduled run for the CI and test workflows aka "nightlies" should be 

### ISSUE THREAD

**Issue by sbuerk** [TYPO3-Documentation/codesnippet#10]
I think it make sense to add daily/scheduled execution
of the defined worklow jobs aka `nighlies`.

**Comment by sypets** [comment]
I would like to second this :smile: The jobs may at one point fail and if not run regularly, this is not noticed until a PR is pushed. 

@sbuerk can you point to a repo which could be used as template for TYPO3 (where the CI run can be used as example)? While this is not strictly necessary, I find it tremendously helpful as contributor if there is a common way to do things and not every GitHub workflow file and how the checks and run are different. I suspect this would be either styleguide or tea?

**Comment by sbuerk** [comment]
@sypets Sure. Personally I think is not really possible to have "this one repository example".
Each project/extension/package has own need's which have to be taken care.

Working on have multiple examples using `typo3/testing-framework`
along with `Build/Scripts/runTests.sh` is some kind of a side-task
for me. Thus having a couple of examples how it may be done.

Single-core testing, multi-core testing, cgl, unit, functional,
acceptance, acceptance-command-line testing and so forth, you
name it.

Having tools like php included or not, with several packages.

And having "scheduled" job is a general CI topic which makes
sense to have.

I already created a issue to extend the README.rst .. maybe
it would make sense to note the "scheduled" execution there
with the `benefit`of having it.
